module.exports = {
	title: "Surface Displacements",
	subtitle: "Poems from the Three-Way Continental Divide",
	description: "",
	rooturl: "https://3rivers.netlify.app",
	file: "index3rivers",
	//bgcolors: ["#768387", "#556D7F"],
	bgcolors: ["#556D7F"],
	authorurl: "https://sheilapacka.com/index.html",
	author: "Sheila Packa",
	otherbooks: ["Mother Tongue", "Echo & Lightning", "Cloud Birds", "Migrations", "Night Train Red Dust: Poems of the Iron Range", "Surface Displacements"],	
	copyright: "Copyright ©2022 Sheila Packa<br/> All Rights Reserved<br/> Printed in the United States of America<br/>",
	isbn: "ISBN: 978-1-947787-36-0<br/>Library of Congress Control Number:<br/>",
	publisher: "Wildwood River Press",
	sections: [
		{ 
			id: "sectionfrontmatter",
			poems: ["frontmatter", "grantthanks"],
			cssclasses: ["notoc"]
		},
		{ 
			id: "sectiontoc",
			title: "Table of Contents",
			cssclasses: ["pagenonumbers", "notoc"],
			generatorf: "generateTOC",
		},
		{ 
			id: "sectionwaterfilledminepit",
			title: "I. In The Water",
			cssclasses: ["pagestartnumbers"],
			poems: ["waterfilledminepit"]
		},
		{
			id: "sectionsurfacedisplacements",
			title: "II. Surface Displacements",
			poems: ["surfacedisplacements"]
		},
		{
			id: "sectionthreerivers",
			title: "III. Three Rivers",
			poems: [
				"fourstones",
				"notdrowning",
				"soliloquy",
				"levels",
				"aquasienna",
				//"underwatermusic",
				"breaking",
				"horses",
				"erosions",
				"disappearingearth",
				"minntacbrand",
				"dialectics",
				"vulture",
				"attheedge",
				"antennafarm",
				"losingground",
				"trace",
				"brokenshell",
				"canadiangeese",
				"strangebeastsboulderlake",
				"wayfinding",
				"snail",
				"blue"]
		},
		{
			id: "sectiontheotherworld",
			title: "IV. The Otherworld",
			poems: [
				//"theotherworld",
				"veneboati",
				"kielitongue",
				"satamaharbor",
				"poem15",
				"rannallaonthebeach",
				"kaantaatotranslate",
				"katsoatolook",
				"hamahakkispider",
				"roukaafood",
				"lautasenplates",
				"hevonenhorse",
				"sammalmoss",
				"mitajossotawhatifawar",
				"kuppiJakalacuplichen",
				"talviwinter",
				"sunnuntaisunday",
				"revontuletauroraborealis",
				"kengatshoes"
			]
		},
		{
			id: "sectionheadwaters",
			title: "V. Headwaters",
			poems: [
				"identity",
				"current",
				"pussywillows",
				"noothermorninglikethis",
				"weight",
				"names",
				"thedarkseason",
				"westtworivers",
				"stlouisriverroute",
				"atthethreshold",
				"departure",
				"mapthewayback",
				"halffallenone",
				"luck",
				"yoni",
				"spring",
				"aghazalwithoutsinking",
				"odetowhere",
				"dawn"
			]
		},
		{
			id: "sectionessay",
			title: "VI. Displacements: An Essay",
			poems: ["essay"]
		},
		{
			id: "sectionnotes",
			title: "VII. Notes and Acknowledgments",
			poems: ["notes3rivers","workcited", "acknowledgments","bio"]
		},
	],
	poemids: [
		"waterfilledminepit",
		"surfacedisplacements",
		"aquasienna",
		"notdrowning",
		"underwatermusic",
		"noothermorninglikethis",
		"yoni",
		"soliloquy",
		"breaking",
		"horses",
		"erosions",
		"disappearingearth",
		"minntacbrand",
		"antennafarm",
		"losingground",
		"trace",
		"levels",
		"attheedge",
		"brokenshell",
		"vulture",
		"canadiangeese",
		"strangebeastsboulderlake",
		"identity",
		"wayfinding",
		"snail",
		"dialectics",
		"fourstones",
		"blue",
		"theotherworld",
		"veneboati",
		"kielitongue",
		"satamaharbor",
		"rannalaonthebeach",
		"kaantaatotranslate",
		"katsoatolook",
		"hamahakkispider",
		"roukafood",
		"lautasenplates",
		"hevonenhorse",
		"sammalmoss",
		"mitajossotawhatifawar",
		"kuppiJakalacuplichen",
		"talviwinter",
		"sunnuntaisunday",
		"revontuletauroraborealis",
		"kengatshoes",
		"pussywillows",
		"current",
		"names",
		"thedarkseason",
		"westtworivers",
		"atthethreshold",
		"departure",
		"weight",
		"mapthewayback",
		"halffallenone",
		"luck",
		"spring",
		"stlouisriverroute",
		"aghazalwithoutsinking",
		"odetowhere",
		"dawn",
		"afterword",
		"acknowledgments"
	],
}
