module.exports = {
	title: "echo & lightning",
	subtitle: "",
	description: "",
	rooturl: "https://3rivers.netlify.app",
	file: "indexecholightning",
	bgcolors: ["#283247"],
	authorurl: "https://sheilapacka.com/index.html",
	author: "Sheila Packa",
	copyright: "Copyright ©2010 Sheila Packa<br/> All Rights Reserved<br/> Printed in the United States of America<br/>",
	isbn: "ISBN: 978-0-9843777-1-8<br/>Library of Congress Control Number: 2010935470<br/>",
	publisher: "Wildwood River Press",
	sections: [
		{ 
			id: "sectionfrontmatter",
			poems: ["frontmatter", "grantthanks"],
			cssclasses: ["pagenonumbers", "notoc"]
		},
		{ 
			id: "sectioninscription",
			inscription: "to Kathy and the cello",
			cssclasses: ["pagenonumbers", "notoc"]
		},
		{ 
			id: "sectiontoc",
			title: "Table of Contents",
			cssclasses: ["pagenonumbers", "notoc"],
			generatorf: "generateTOC",
		},
		{ 
			id: "sectionI",
			title: "I",
			cssclasses: ["pagestartnumbers"],
			poems: 
			[
				"dream",
				"twelvetonegeese",
				"northandsouth",
				"loverootsilkthread",
				"raspberrycanes",
				"thunderperfectmind",
				"tothewind",
				"threshold",
				"swan",
				"wolfmoon",
				"centeroffire",
				"leda1",
				"leda2",
				"gift3",
				"ascent",
				"sky",
			]
		},
		{
			id: "sectionII",
			title: "II",
			poems: [
				"withoutbridge",
				"immersion",
				"hiddenthings",
				"betweenusweareavessel",
				"strangesymmetry",
				"notstreambuteddy",
				"after",
				"helpless",
				"songeurydyce",
				"shore",
				"vigil",
				"mouth",
				"battering",
				"displacement",
				"whatsea",
				"riverbegins",
				"invisibleembrace",
				"nocturnesnow",
				"breakinglight",
			]
		},
		{
			id: "sectionIII",
			title: "III",
			poems: [
				"lovenevermeantsky",
				"butterfly",
				"fiddleheads",
				"confluence",
				"thecircleidraw",
				"incantationmuse",
				"saltlotswife",
				"middlepassagemarymagdalene",
				"dusk",
				"fallingstar",
				"inthebeginning",
				"intoshore",
				"thecalling",
				"mylovevillanelle",
				"whatsfound",
				"lovegoeson",
				"whatifastar",
			]
		},
		{
			id: "sectionacknowledgments",
			title: "Acknowledgments",
			poems: [
				"acknowledgments"
			]
		},
	],
	poemids: [
		"frontmatter",
		"dream",
		"twelvetonegeese",
		"northandsouth",
		"loverootsilkthread",
		"raspberrycanes",
		"thunderperfectmind",
		"tothewind",
		"threshold",
		"swan",
		"wolfmoon",
		"centeroffire",
		"leda1",
		"leda2",
		"gift3",
		"ascent",
		"sky",
		"bluesbreakup",
		"withoutbridge",
		"immersion",
		"hiddenthings",
		"betweenusweareavessel",
		"strangesymmetry",
		"notstreambuteddy",
		"after",
		"helpless",
		"songeurydyce",
		"shore",
		"vigil",
		"mouth",
		"battering",
		"displacement",
		"whatsea",
		"riverbegins",
		"invisibleembrace",
		"nocturnesnow",
		"breakinglight",
		"hull",
		"lovenevermeantsky",
		"butterfly",
		"fiddleheads",
		"confluence",
		"thecircleidraw",
		"incantationmuse",
		"saltlotswife",
		"middlepassagemarymagdalene",
		"dusk",
		"fallingstar",
		"inthebeginning",
		"intoshore",
		"thecalling",
		"mylovevillanelle",
		"whatsfound",
		"lovegoeson",
		"whatifastar",
		"suspendedinblue",
		"afterword"
	],
}
