module.exports = {
	title: "Night Train Red Dust",
	subtitle: "Poems of the Iron Range",
	description: "",
	rooturl: "https://3rivers.netlify.app",
	bgcolors: ["#4E4340"],
	file: "indexnighttrain",
	authorurl: "https://sheilapacka.com/index.html",
	author: "Sheila Packa",
	copyright: "Copyright ©2014 Sheila Packa<br/> All Rights Reserved<br/> Printed in the United States of America<br/>",
	isbn: "ISBN: 978-0-9843777-7-0<br/>Library of Congress Control Number: 2014936958<br/>",
	publisher: "Wildwood River Press",
	sections: [
		{ 
			id: "sectionfrontmatter",
			poems: ["frontmatter", "grantthanks"],
			cssclasses: ["notoc"]
		},
		{ 
			id: "sectioninscription",
			inscription: `
These roads will take you into your own country.<br/>
— Muriel Rukeyser`,
			cssclasses: ["pagenonumbers", "notoc"]
		},
		{ 
			id: "sectiontoc",
			title: "Table of Contents",
			cssclasses: ["pagenonumbers", "notoc"],
			generatorf: "generateTOC",
		},
		{ 
			id: "sectiontrack1",
			title: "Track I: Night Train",
			cssclasses: ["pagestartnumbers"],
			poems: 
			[
				"mygeology",
				"strangehighway",
				"medicineontheironrange",
				"work",
				"northstar",
				"vestiges",
				"midwife",
				"notjustbread",
				"grace",
				"ministry",
				"olivermine",
				"unknownwomanminer",
				"oldmusic",
				"accordionist",
				"patchers",
				"brokenenglish",
				"strawberryharvest",
				"timber",
				"foxnolongerhidden",
				"pour",
				"memento",
				"thecost",
				"rendezvous",
				"kegparty",
				"rumors",
				"historyofthedandelion",
				"refuge",
				"bonfireofroses",
			]
		},
		{
			id: "sectiontrack2",
			title: "Track II: Red Dust",
			poems: [
				"derailment",
				"iron",
				"sketch",
				"blindpig",
				"immigration",
				"metamorphosis",
				"blackice",
				"elements",
				"equinox",
				"boundarywaters",
				"conjuringabear",
				"crows",
				"memorythemine",
				"stairwell",
				"rupture",
				"steamsong",
				"redstars",
				"horses",
				"rhubarb",
				"neighbor",
				"grouse",
				"meteor",
				"consanguinity",
				"womenwelders",
				"marthaslesson",
				"zenithcity",
				"thetremont",
				"minepitblessing",
				"lostdestination",
				"lighting",
				"scroll",
				"dictateofwind",
				"aroundthehorn",
			]
		},
		{
			id: "sectionacknowledgments",
			title: "Acknowledgments",
			poems: [
				"workcited",
				"acknowledgments"
			]
		},
	],
	poemids: [
		"frontmatter",
		"grantthanks",
		"bookinscription",
		"mygeology",
		"strangehighway",
		"medicineontheironrange",
		"work",
		"northstar",
		"vestiges",
		"midwife",
		"notjustbread",
		"grace",
		"ministry",
		"olivermine",
		"unknownwomanminer",
		"oldmusic",
		"accordionist",
		"patchers",
		"brokenenglish",
		"strawberryharvest",
		"timber",
		"foxnolongerhidden",
		"pour",
		"memento",
		"thecost",
		"rendezvous",
		"kegparty",
		"rumors",
		"historyofthedandelion",
		"refuge",
		"bonfireofroses",
		"vermiliontrail",
		"derailment",
		"iron",
		"sketch",
		"blindpig",
		"immigration",
		"metamorphosis",
		"blackice",
		"elements",
		"equinox",
		"boundarywaters",
		"conjuringabear",
		"crows",
		"memorythemine",
		"stairwell",
		"rupture",
		"steamsong",
		"redstars",
		"horses",
		"rhubarb",
		"neighbor",
		"grouse",
		"meteor",
		"consanguinity",
		"womenwelders",
		"marthaslesson",
		"zenithcity",
		"thetremont",
		"minepitblessing",
		"lostdestination",
		"lighting",
		"scroll",
		"dictateofwind",
		"aroundthehorn",
		"workcited",
		"acknowledgments"
	],
}
